### ISSUE TITLE
division by zero raised when requesting history of a recently listed stock

### ISSUE THREAD

**Issue by portefeuille** [dpguthrie/yahooquery#144]
**Describe the bug**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/samuel/Library/Python/3.9/lib/python/site-packages/yahooquery/ticker.py", line 1279, in history
    df = self._historical_data_to_dataframe(data, params, adj_timezone)
  File "/Users/samuel/Library/Python/3.9/lib/python/site-packages/yahooquery/ticker.py", line 1308, in _historical_data_to_dataframe
    d[symbol] = _history_dataframe(data[symbol], daily, adj_timezone)
  File "/Users/samuel/Library/Python/3.9/lib/python/site-packages/yahooquery/utils/__init__.py", line 184, in _history_dataframe
    data_dict[event] = _event_as_srs(event_data, event)
  File "/Users/samuel/Library/Python/3.9/lib/python/site-packages/yahooquery/utils/__init__.py", line 167, in _event_as_srs
    values = [d["numerator"] / d["denominator"] for d in event_data.values()]
  File "/Users/samuel/Library/Python/3.9/lib/python/site-packages/yahooquery/utils/__init__.py", line 167, in <listcomp>
    values = [d["numerator"] / d["denominator"] for d in event_data.values()]
ZeroDivisionError: division by zero
```

**To Reproduce**

```
from yahooquery import Ticker
stock = Ticker('ALCBI.PA')
data = stock.history(period='2y', interval='1wk', adj_ohlc=True)
```

**Expected behavior**
Not sure

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Python 3.9.6
 - yahooquery 2.3.0

**Comment by maread99** [comment]
Hi @portefeuille

This error is being raised as a result of the split information held by yahoo being, in would seem, inaccurate:
```
{'splits': {'1641769200': {'date': 1641801600,
   'numerator': 1,
   'denominator': 0,
   'splitRatio': '1:0'},
  '1642978800': {'date': 1643184000,
   'numerator': 5,
   'denominator': 4,
   'splitRatio': '5:4'}}}
```
The first entry, with timestamp 1641769200 (2022-01-10) has the split defined as 1:0 (free shares 🎉) - this is why the `ZeroDivisionError` is being raised. The actual split was 10 for 1. On the news reel I can't see any split mentioned for the second entry (2022-01-26). All a bit odd.

Obviously data should still be returned. Prior to v2.3 the implementation was different and would have resulted in this circumstance being represented by a `float('inf')` value in the splits column. I'm going to add a commit to current PR #141 to restore that behavior.
