### ISSUE TITLE
TypeError: an integer is required (got type NoneType) on few symbols (Example: CAM.WA)

### ISSUE THREAD

**Issue by irezumi** [dpguthrie/yahooquery#145]
I got an error message, while trying to download a bunch of data from a list of tickers:

	TypeError: an integer is required (got type NoneType)

if 'regularMarketTime' is None in the meta data:

`{'meta': {'currency': None, 'symbol': 'CAM.WA', 'exchangeName': 'WSE', 'instrumentType': 'EQUITY', 'firstTradeDate': 1510646400, 'regularMarketTime': None, 'gmtoffset': 3600, 'timezone': 'CET', 'exchangeTimezoneName': 'Europe/Warsaw', 'chartPreviousClose': 0.71, 'priceHint': 2, 'currentTradingPeriod': {'pre': {'timezone': 'CET', 'start': 1676016000, 'end': 1676016000, 'gmtoffset': 3600}, 'regular': {'timezone': 'CET', 'start': 1676016000, 'end': 1676045100, 'gmtoffset': 3600}, 'post': {'timezone': 'CET', 'start': 1676045100, 'end': 1676045100, 'gmtoffset': 3600}}, 'dataGranularity': '1d', 'range': '2y', 'validRanges': ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'ytd', 'max']}, 'timestamp': [1612944000, ...`

Code:

```
from yahooquery import Screener
from yahooquery import Ticker

tickers_list = ["MSFT", "TSLA", "CAM.WA"]
dataframe = Ticker(tickers_list, progress=True).history(period='2y', interval='1d')

print(dataframe)
```

Output:
```
Error:
python yahooquery_error.py
100%|█████████████████████████████| 3/3 [00:00<00:00,  6.23it/s]
Traceback (most recent call last):
  File "C:\Repositories\RocketScience\yahooquery_error.py", line 5, in <module>
    dataframe = Ticker(tickers_list, progress=True).history(period='2y', interval='1d')
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\yahooquery\ticker.py", line 1279, in history
    df = self._historical_data_to_dataframe(data, params, adj_timezone)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\yahooquery\ticker.py", line 1308, in _historical_data_to_dataframe
    d[symbol] = _history_dataframe(data[symbol], daily, adj_timezone)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\yahooquery\utils\__init__.py", line 193, in _history_dataframe
    index = _get_daily_index(data, index, adj_timezone)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\yahooquery\utils\__init__.py", line 125, in _get_daily_index
    last_trade = pd.Timestamp.fromtimestamp(timestamp)
  File "pandas\_libs\tslibs\timestamps.pyx", line 1477, in pandas._libs.tslibs.timestamps.Timestamp.fromtimestamp
TypeError: an integer is required (got type NoneType)
```

I'm using following packages:

```
pip install yahooquery --upgrade
Requirement already satisfied: yahooquery in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (2.3.0)
Requirement already satisfied: tqdm>=4.54.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from yahooquery) (4.62.3)
Requirement already satisfied: lxml>=4.9.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from yahooquery) (4.9.2)
Requirement already satisfied: pandas>=0.24.0 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from yahooquery) (1.5.3)
Requirement already satisfied: requests-futures>=1.0.0 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from yahooquery) (1.0.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.24.0->yahooquery) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.24.0->yahooquery) (2.8.2)
Requirement already satisfied: numpy>=1.20.3 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.24.0->yahooquery) (1.22.2)
Requirement already satisfied: requests>=1.2.0 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from requests-futures>=1.0.0->yahooquery) (2.28.2)
Requirement already satisfied: colorama in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from tqdm>=4.54.1->yahooquery) (0.4.4)
Requirement already satisfied: six>=1.5 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.24.0->yahooquery) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (1.26.8)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (3.3)

```

```
pip install pandas --upgrade
Requirement already satisfied: pandas in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.20.3 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas) (1.22.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\danny\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

```

With this error the complete progress stopped, without any data.

**Comment by maread99** [comment]
Thanks for raising this @irezumi.

This is happening because the v2.3 changes assumed that all stocks report a last trade time. Apparently this isn't the case. I'll add a commit to #141 to fix.

In the meantime you could change the following lines of your local installed copy of yahooquery...

https://github.com/dpguthrie/yahooquery/blob/81b3e0918da399b406ec648318bea06522fad3a1/yahooquery/utils/__init__.py#L125-L127

to...
```python
if timestamp is None:
    has_live_indice = False
else:
    last_trade = pd.Timestamp.fromtimestamp(timestamp, tz="UTC")
    has_live_indice = index_utc[-1] >= last_trade - pd.Timedelta(2, "S")
```
