### ISSUE TITLE
Key error for all symbols

### ISSUE THREAD

**Issue by eltirobert** [dpguthrie/yahooquery#230]
As of last night, it is giving key errors for all symbols. For example:

from yahooquery import Ticker

share = Ticker('aapl')
print(share.grading_history)

gives:

Traceback (most recent call last):
  File "/Users/homemac/Desktop/My Files/My Documents/Programming/Programming (Stocks and Scraping 2)/Python Scripts/Old Stock Methods/Trial Stock Methods/Stock Methods Final/trial30.py", line 5, in <module>
    print(share.grading_history)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/homemac/Library/Python/3.12/lib/python/site-packages/yahooquery/ticker.py", line 744, in grading_history
    return self._quote_summary_dataframe("upgradeDowngradeHistory")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/homemac/Library/Python/3.12/lib/python/site-packages/yahooquery/ticker.py", line 112, in _quote_summary_dataframe
    return self._to_dataframe(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/homemac/Library/Python/3.12/lib/python/site-packages/yahooquery/ticker.py", line 120, in _to_dataframe
    data[symbol][kwargs.get("data_filter")]
    ~~~~^^^^^^^^
KeyError: 'aapl'

It just starting giving this last night.

**Comment by eltirobert** [comment]
OK, should have tried v. 2.3.3. It works with the latest version.

**Comment by dkim777** [comment]
My pip3 can't find this version.

pi@raspberrypi:~ $ sudo pip3 install yahooquery==2.3.3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yahooquery==2.3.3
  Could not find a version that satisfies the requirement yahooquery==2.3.3 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.3.0, 2.3.1, 2.3.2)
No matching distribution found for yahooquery==2.3.3

**Comment by eltirobert** [comment]
Download the tar.gz file from here on gihub and install through terminal.

**Comment by dpguthrie** [comment]
This should work now (probably depending on location though) - please reopen if not.
