### ISSUE TITLE
2.3.7 still not working in EU

### ISSUE THREAD

**Issue by ibart** [dpguthrie/yahooquery#249]
**Describe the bug**
pip install yahooquery==2.3.7

**To Reproduce**
```
from yahooquery import Ticker

aapl = Ticker('aapl')

print(aapl.summary_detail)
```

**Errors:**
```
Traceback (most recent call last):
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 1076, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 1018, in _handle_chunk
    value = self._fp._safe_read(amt)  # type: ignore[union-attr]
  File "/usr/lib/python3.10/http/client.py", line 631, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ibart/.local/lib/python3.10/site-packages/urllib3/response.py", line 715, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='finance.yahoo.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/bofo/python/getquote.py", line 3, in <module>
    aapl = Ticker('aapl')
  File "/home/ibart/.local/lib/python3.10/site-packages/yahooquery/ticker.py", line 93, in __init__
    super(Ticker, self).__init__(**kwargs)
  File "/home/ibart/.local/lib/python3.10/site-packages/yahooquery/base.py", line 950, in __init__
    self.session = setup_session(self.session, self._setup_url)
  File "/home/ibart/.local/lib/python3.10/site-packages/yahooquery/utils/__init__.py", line 1405, in setup_session
    response = session.post(
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/ibart/.local/lib/python3.10/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='finance.yahoo.com', port=443): Read timed out.

```
**Using an USA's VPN it is working as it used to:**
`{'aapl': {'maxAge': 1, 'priceHint': 2, 'previousClose': 198.11, 'open': 197.53, 'dayLow': 197.02, 'dayHigh': 198.3999, 'regularMarketPreviousClose': 198.11, 'regularMarketOpen': 197.53, 'regularMarketDayLow': 197.02, 'regularMarketDayHigh': 198.3999, 'dividendRate': 0.96, 'dividendYield': 0.0049, 'exDividendDate': '2023-11-10 01:00:00', 'payoutRatio': 0.1533, 'fiveYearAvgDividendYield': 0.82, 'beta': 1.308, 'trailingPE': 32.28268, 'forwardPE': 27.632168, 'volume': 114815314, 'regularMarketVolume': 114815314, 'averageVolume': 55190104, 'averageVolume10days': 63109570, 'averageDailyVolume10Day': 63109570, 'bid': 196.56, 'ask': 196.6, 'bidSize': 1200, 'askSize': 800, 'marketCap': 3072766771200, 'fiftyTwoWeekLow': 124.17, 'fiftyTwoWeekHigh': 199.62, 'priceToSalesTrailing12Months': 8.016924, 'fiftyDayAverage': 183.7876, 'twoHundredDayAverage': 177.569, 'trailingAnnualDividendRate': 0.94, 'trailingAnnualDividendYield': 0.004744839, 'currency': 'USD', 'fromCurrency': None, 'toCurrency': None, 'lastMarket': None, 'coinMarketCapLink': None, 'algorithm': None, 'tradeable': False}}
`

**Comment by RudyNL** [comment]
From the Netherlands `yahooquery` v2.3.7 is working fine
```
>>> from yahooquery import Ticker
>>> 
>>> aapl = Ticker('aapl')
>>> 
>>> print(aapl.summary_detail)
{'aapl': {'maxAge': 1, 'priceHint': 2, 'previousClose': 198.11, 'open': 197.53, 'dayLow': 197.02, 'dayHigh': 198.3999, 'regularMarketPreviousClose': 198.11, 'regularMarketOpen': 197.53, 'regularMarketDayLow': 197.02, 'regularMarketDayHigh': 198.3999, 'dividendRate': 0.96, 'dividendYield': 0.0049, 'exDividendDate': '2023-11-10 01:00:00', 'payoutRatio': 0.1533, 'fiveYearAvgDividendYield': 0.82, 'beta': 1.308, 'trailingPE': 32.28268, 'forwardPE': 30.11738, 'volume': 128538401, 'regularMarketVolume': 128538401, 'averageVolume': 55190104, 'averageVolume10days': 63109570, 'averageDailyVolume10Day': 63109570, 'bid': 196.56, 'ask': 196.6, 'bidSize': 1000, 'askSize': 800, 'marketCap': 3072766771200, 'fiftyTwoWeekLow': 124.17, 'fiftyTwoWeekHigh': 199.62, 'priceToSalesTrailing12Months': 8.016924, 'fiftyDayAverage': 183.7876, 'twoHundredDayAverage': 177.569, 'trailingAnnualDividendRate': 0.94, 'trailingAnnualDividendYield': 0.004744839, 'currency': 'USD', 'fromCurrency': None, 'toCurrency': None, 'lastMarket': None, 'coinMarketCapLink': None, 'algorithm': None, 'tradeable': False}}
>>> 
```

**Comment by ibart** [comment]
> From the Netherlands `yahooquery` v2.3.7 is working fine
> 
> ```
> >>> from yahooquery import Ticker
> >>> 
> >>> aapl = Ticker('aapl')
> >>> 
> >>> print(aapl.summary_detail)
> {'aapl': {'maxAge': 1, 'priceHint': 2, 'previousClose': 198.11, 'open': 197.53, 'dayLow': 197.02, 'dayHigh': 198.3999, 'regularMarketPreviousClose': 198.11, 'regularMarketOpen': 197.53, 'regularMarketDayLow': 197.02, 'regularMarketDayHigh': 198.3999, 'dividendRate': 0.96, 'dividendYield': 0.0049, 'exDividendDate': '2023-11-10 01:00:00', 'payoutRatio': 0.1533, 'fiveYearAvgDividendYield': 0.82, 'beta': 1.308, 'trailingPE': 32.28268, 'forwardPE': 30.11738, 'volume': 128538401, 'regularMarketVolume': 128538401, 'averageVolume': 55190104, 'averageVolume10days': 63109570, 'averageDailyVolume10Day': 63109570, 'bid': 196.56, 'ask': 196.6, 'bidSize': 1000, 'askSize': 800, 'marketCap': 3072766771200, 'fiftyTwoWeekLow': 124.17, 'fiftyTwoWeekHigh': 199.62, 'priceToSalesTrailing12Months': 8.016924, 'fiftyDayAverage': 183.7876, 'twoHundredDayAverage': 177.569, 'trailingAnnualDividendRate': 0.94, 'trailingAnnualDividendYield': 0.004744839, 'currency': 'USD', 'fromCurrency': None, 'toCurrency': None, 'lastMarket': None, 'coinMarketCapLink': None, 'algorithm': None, 'tradeable': False}}
> >>> 
> ```

HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v1/test/getcrumb (Caused by ResponseError('too many 500 error responses'))

Not working.

**Comment by ibart** [comment]
> ut it only happens when the connection is asynchronous. I am in Spain.

Yes! It was **asynchronous=True**

Thanks.
