### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_futures'

### ISSUE THREAD

**Issue by antoinecomp** [dpguthrie/yahooquery#8]
Hey ! Your great library is working fine on my Jupyter, however in a mere file I have some issues. When importing Ticker I get the following error:

```
C:\ProgramData\Anaconda3\envs\homework3\python.exe C:/Users/antoi/Documents/Programming/portfolio-advisor/run.py
Traceback (most recent call last):
  File "C:/Users/antoi/Documents/Programming/portfolio-advisor/run.py", line 1, in <module>
    from dashboard.app import app #, auth
  File "C:\Users\antoi\Documents\Programming\portfolio-advisor\dashboard\app.py", line 8, in <module>
    from .pages import header, imap, stock, markets, stocks
  File "C:\Users\antoi\Documents\Programming\portfolio-advisor\dashboard\pages\stocks.py", line 11, in <module>
    from yahooquery import Ticker
  File "C:\Users\antoi\AppData\Roaming\Python\Python37\site-packages\yahooquery\__init__.py", line 3, in <module>
    from .ticker import Ticker  # noqa
  File "C:\Users\antoi\AppData\Roaming\Python\Python37\site-packages\yahooquery\ticker.py", line 12, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

Process finished with exit code 1
```

I tried to install it with pip and pip3 but it never changer anything:

```
(homework3) C:\Users\antoi\Documents\Programming\portfolio-advisor>pip3 install requests --upgrade
Requirement already up-to-date: requests in c:\users\antoi\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (2.23.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\antoi\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from reque
sts) (2.9)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\antoi\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python3
7\site-packages (from requests) (1.25.8)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\antoi\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from
requests) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\antoi\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from
 requests) (2019.11.28)

(homework3) C:\Users\antoi\Documents\Programming\portfolio-advisor>python -m pip install requests --upgrade
Collecting requests
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\homework3\lib\site-packages (from requests) (2019.11.28)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\programdata\anaconda3\envs\homework3\lib\site-packages (from requests) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\envs\homework3\lib\site-packages (from requests) (1.25.8)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\programdata\anaconda3\envs\homework3\lib\site-packages (from requests) (3.0.4)
ERROR: quandl 3.5.0 requires more-itertools, which is not installed.
ERROR: fxcmpy 1.2.6 requires socketIO-client, which is not installed.
ERROR: findatapy 0.1.7 requires keyring, which is not installed.
ERROR: findatapy 0.1.7 requires numba, which is not installed.
ERROR: findatapy 0.1.7 requires openpyxl, which is not installed.
ERROR: findatapy 0.1.7 requires pandas-datareader, which is not installed.
ERROR: findatapy 0.1.7 requires redis, which is not installed.
ERROR: findatapy 0.1.7 requires statsmodels, which is not installed.
ERROR: findatapy 0.1.7 requires twython, which is not installed.
Installing collected packages: requests
  Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0
Successfully installed requests-2.23.0
```

Do you have any idea?

**Comment by dpguthrie** [comment]
It might be the version that you've downloaded.  One of the versions I released did not have that as a requirement and would fail.  Have you tried upgrading?

`pip install yahooquery --upgrade`
